language: python
python:
    - "2.7"
addons:
    apt:
        packages:
            - uuid-dev
            - swig
            - libldap2-dev
# The sed command is a terrible hack: we can't easily install koji on Ubuntu.
# PDC does not need it, it is a dependency of kobo. However, PDC does not use
# any part of kobo that would actively use koji, se we just delete the
# offending import.
install:
    - pip install -U pip wheel coveralls
    - pip install -r requirements/devel.txt
    - sed -i -E '/import (koji|rpm)/d' $(python -vc 'import kobo.rpmlib' 2>&1 | grep 'import kobo.rpmlib' | awk '{print$NF}' | sed 's/pyc$/py/')
script:
    - coverage run --source=contrib,pdc --omit='*tests.py,*/migrations/*,pdc/settings*' manage.py test --settings pdc.settings_test
    - make flake8
    - make extra_test
after_success:
    coveralls
cache:
    directories:
        - $HOME/.cache/pip
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
